variable "env" { default = "dev" }
variable "vpc_cidr" { default = "10.0.0.0/16" }
variable "azs" { default = ["us-east-1a", "us-east-1b"] }
variable "public_subnet_cidrs" { default = ["10.0.1.0/24", "10.0.2.0/24"] }
variable "private_subnet_cidrs" { default = ["10.0.10.0/24", "10.0.11.0/24"] }
variable "data_subnet_cidrs" { default = ["10.0.20.0/24", "10.0.21.0/24"] }
variable "instance_class" { default = "db.t3.micro" }
variable "rds_storage" { default = 20 }
variable "multi_az" { default = false }
variable "backup_retention_days" { default = 7 }
variable "db_name" { default = "sga_db" }
variable "db_username" { default = "sga_admin" }
variable "db_password" { default = "changeme123" }
variable "ecs_cpu" { default = 256 }
variable "ecs_memory" { default = 512 }
variable "desired_count" { default = 1 }
variable "container_port" { default = 8000 }
variable "node_type" { default = "cache.t3.micro" }
variable "certificate_arn" { default = "" } # no usaremos HTTPS en dev
variable "image_tag" { default = "latest" }